# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b6b913ca-6cf0-4392-9da0-d46d13f6adc5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b6b913ca-6cf0-4392-9da0-d46d13f6adc5".device = "/dev/disk/by-uuid/b6b913ca-6cf0-4392-9da0-d46d13f6adc5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AAE2-F545";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/slave" =
    { device = "/dev/disk/by-uuid/ae6d755d-c6de-4e93-89b8-5fdecfeca252";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
